events {
    worker_connections 1024; # Fixed: Required by NGINX
}

http {
    include       /etc/nginx/mime.types; # Good practice: Ensures CSS/JS/images load correctly
    default_type  application/octet-stream;

    server {
        listen 443 ssl;
        # listen [::]:443 ssl;

        server_name localhost;

        root /var/www/html;
        index index.php index.html;

        # SSL security
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        ssl_protocols TLSv1.3;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$; # Split before including params
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}

# events {

# }

# http {
#     server {
#         listen 443 ssl;
#         # listen [::]:443 ssl;
#         # SSL security
#         server_name localhost;
#         # to complete later ENV variables

#         # server_name localhost ${DOMAIN_NAME} 127.0.0.1;
#         # server_name www.${DOMAIN_NAME};

#         root /var/www/html;
#         index index.php index.html;

#         ssl_certificate /etc/nginx/ssl/inception.crt;
#         ssl_certificate_key /etc/nginx/ssl/inception.key;

#         ssl_protocols TLSv1.3;

#         location / 
#         {
#             try_files $uri $uri/ /index.php?$args;
#         }

#         location ~ \.php$
#         {
#             include fastcgi_params;
#             fastcgi_split_path_info ^(.+\.php)(/.+)$;

#             fastcgi_pass test_wp:9000;
#             fastcgi_index index.php;
#             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#             fastcgi_param PATH_INFO $fastcgi_path_info;
#         }
#     }
# }

# fastcgi_pass -> container name
# workpress - php language
# docker run -d -p 443:443 --name [container name] --network [network name] [image name]
# docker run -d -p 443:443 --name [container name] --network [network name] -v wp_data:/var/www/html [image_name] 